### PR TITLE
Add basic support for VSI sentences

### PR DESCRIPTION
**Pull request by johnmartel**
This comes as a request from the Canadian Coast Guard who are using the [dma-ais/AisCoverage](https://github.com/dma-ais/AisCoverage) project and wanted to be able to analyze coverage by signal strength.

I had a limited amount of time to work out a solution, so this may not be as clean as I would like it to be.

The idea is pretty simple:
- keep incoming VDM/VDO messages for two seconds so that they can be searched for when receiving a VSI sentence and be linked together
- when receiving a VSI sentence, wrap it, along with its related VDM in an AisPacket
- I am relying on the comment block of the sentence in most cases to correlate between VDM and VSI, as, at least in the case of the Canadian Coast Guard, sentences are sent with a comment block taking the form: `\c:[timestamp to the second],C:[message counter for this station],s:[station unique id]*[checksum]\`

This PR goes hand in hand with [this pull request](https://github.com/dma-ais/AisCoverage/pull/1) on [dma-ais/AisCoverage](https://github.com/dma-ais/AisCoverage).

When merging this PR, one should be aware that the version number in pom.xml now assumes that semantic versioning is used and that the CCG pre-release identifier has been added to identify my current builds as being from the fork. I think you should get rid of the pre-release identifier, as this will be merged in the original, official repo. A new official distribution with these changes would be greatly appreciated.

Please reach out with any comments/questions :)

Thanks!

### CODE REVIEW

**Comment by tbsalling** [comment]
Hi @johnmartel - thanks a lot for this contribution. It requires to be reviewed on our side before entering the master branch - this will currently be pending due to time constraints; but as soon as I get sufficient time, I shall take a look.

One immediate comment is that I would like to avoid the .mvn/ folder to be included - but I may need to understand better why it is there.

Thanks again for this contribution.

**Comment by johnmartel** [comment]
@tbsalling when reviewing this, if you have any recommendations on writing the code differently to better fit your architecture, please go ahead and I shall make the changes. I am in no way an AIS expert and simply wanted to get things working for the CCG so that they can start analyzing coverage using signal strength. This is actually working quite fine, but I don't like that big "if" statement in the AisPacketParser...

**Comment by johnmartel** [comment]
The Gradle wrapper documentation I was referring to: https://docs.gradle.org/current/userguide/gradle_wrapper.html
The Maven wrapper basically works in the same way and was inspired by the gradle wrapper.

You'll see here that the `.mvn` folder is required because it contains the wrapper code and configuration, so that the script can be run.

**Comment by tbsalling** [comment]
Hi @johnmartel thanks again. I plain simply haven't had time to review this yet; but your contrib is appreciated and not forgotten!

**Comment by tbsalling** [comment]
Hi @johnmartel - I know that this PR has been dangling for quite a while.

The reason for this long idle period is that we are not set to embody VSI sentences in the general product. An additional minor reason is that we do not intend to support both Maven and Gradle. So far we are (still) going with just Maven - and not (yet) the wrapper version. 

So I will mark this PR wontfix for now (to reflect the de facto state, which you may already have deduced :-)). 

We do still very much appreciate your contribution and use of AisLib, though - so thanks for contributing; we hope that you are still happy and productive with the tool.

**Pull request closed without merging**
