### PR TITLE
Json decoders

### PR DESCRIPTION
**Pull request by CallSign-Filter**
Added all of the AisDecoding features and test classes. This will take an `AisMessage` object and decode it to a human-readable json that breaks out all enums and flags. Added documentation on how to use in the README file.

### CODE REVIEW

**Comment by tbsalling** [comment]
Hi - I have had time to review this now. It looks brilliant and very useful. And I like that the code is quite decoupled from the existing AisLib functionality. This gives us the opportunity to separate the enhancement into a sub-project named `ais-lib-json` located as a sibling to e.g. `ais-lib-utils` and `ais-lib-cli`. Could you do that before I merge with master?

**Comment by CallSign-Filter** [comment]
@tbsalling Requested changed were made, thank you for your input and kind words about my contribution. Furthermore, thank you for this project, it is extremely helpful.

**Comment by tbsalling** [comment]
Hi @CallSign-Filter - yup, that's a lot better. 

Could you also move the remaining parts of the new code into ais-lib-json? I am thinking for instance `package dk.dma.ais.message.json_decoder_helpers` in src/main/java - and also `package dk.dma.ais.message_decoders` in src/test/java ?

The goal is that ais-lib-messages is completely free of references to JSON. ais-lib-json should know of ais-lib-messages (and JSON) - but ideally ais-lib-messages should not know anything about JSON.

Thanks in advance!

**Comment by CallSign-Filter** [comment]
@tbsalling You are absolutely right, I had made those changes but I forgot o check the box when committing them. Take a look at that and let me know of any other changes.

**Comment by tbsalling** [comment]
Thank you for the contribution @CallSign-Filter !

**Pull request merged**
